### ISSUE TITLE
Provide pre-verified wasm binary files to confirm functionality

### ISSUE THREAD

**Issue by jserv** [LuisHsu/WasmVM#23]
Since `WasmVM` is under development, it is vital for users to distinguish from the internal problems and wasm files generated by external tools. We can implement `make check` to perform the validation of given wasm files which were checked in advanced.

**Comment by LuisHsu** [comment]
The wabt tool set is development with lex tool, and the messages is really a bit inconvenient to read.

Maybe we can build another binary tool from scratch.

For the test of internal functions, it's my fault that I put the my test data in my build directory and forgot to keep them. Give me some time to rebuild them, or other contributers can help withe the test datas.

**Comment by LuisHsu** [comment]
A new branch [add-tests](https://github.com/LuisHsu/WasmVM/tree/add-tests) is created.

The tests are driven by CTest. It's bundled with CMake, and that makes it suitable for us without more dependencies.
