### ISSUE TITLE
定義 Wasm Structure 的標頭檔

### ISSUE THREAD

**Issue by LuisHsu** [LuisHsu/WasmVM#47]
在 decoder 之外直接操作 bytecode 或 Runtime Instance
語意上和擴充彈性都很糟
因此我們需要先定義出 Wasm 規格內的資料結構，透過這些資料結構來操作
可以參考 doc/images/WasmStructure.svg 把 WasmStructure 都定義在 src/include/structures

**Comment by kevinbird61** [comment]
#65
